dist: bionic
addons:
  ssh_known_hosts: qw2.quakeworld.nu
language: node_js
node_js:
- stable
before_script:
- yarn install --frozen-lockfile
script:
- yarn build
before_install:
- openssl aes-256-cbc -K $encrypted_7a1636384610_key -iv $encrypted_7a1636384610_iv
  -in deploy_rsa.enc -out deploy_rsa -d
after_success:
  - eval "$(ssh-agent -s)"
  - chmod 600 deploy_rsa
  - ssh-add deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: bash deploy/deploy.sh
  on:
      branch: master
