dist: bionic
language: node_js
node_js:
- stable
before_script:
- yarn install
script:
- yarn build
before_install:
- openssl aes-256-cbc -K $encrypted_7a1636384610_key -iv $encrypted_7a1636384610_iv
  -in deploy_rsa.enc -out deploy_rsa -d
